language: csharp
solution: LolAV.sln
branches:
  only:
  - master
  - /^v.*$/
before_deploy:
  - cd ${TRAVIS_BUILD_DIR}/LolAV/bin/Release
  - zip -r ${HOME}/LolAV.zip ./*
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ULlzNszHXOaS2Sf/iuRiyjbbTGOvNpNRycXGdNxgRu7CDwmI1vRMlvH0DNcKxC2pi9YpPXm1vBYeInwtAoz2Yrw7rCQAjxcEcykK7qW6zVvojuxI+vP+RGRjp0d0WYgKi2WC9kTCTgcyBYd2eMAF+Sq3TPtK9N2MB95jLf6DvWdEJI1X/muFVp7m6sqBlqXKye8H5Ja3QBiEvaGYy4ukFVDiI0mMe9UPaQNT8HvH2ema0I7xmfl4g+fVvd+IPMiYsBnhAvi8ba9s9aFLRAk49BGmnjlBkY5IKvOowNUpg0UKhY5Lco5midGIUbxj0pPFm7ZM/l6AwvV4IeO84sWzPhzoglcQeStDde88JkGLEuWXDA7TxSvLgpMjMa1mSSAjAlLfRQ3kyYBvGFyYcFbcXi2UnwCyCms8855WPop5s3qUjLEtviuPvsZSbBZL5Hjumh4FYO++4qfXMfmtu1U3FajX9WNdFzE0oka7aKP+GEf173VuZs1NmyKglr0ZnD2U+2evfHZ5pVfr5IZL1InW2Ua4xt+YgDMVANbRt0h2A49BI8kPVOENoCcCbgRZq5s2THcvmkmxp7fxKe2FT7dUgmBiYv9VbrdnYmrADaeVGTLbCif2H8TeoJpeB+7L0p/HQJKVYBGcE+mZpExiOAXVmEb+qax1b8c1pz5ECfduE00=
  file: '${HOME}/LolAV.zip'
  on:
    repo: PixelHir/lolav
